import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { IndianFood } from '../models/IndianFood';

dotenv.config();

const foods = [
  // ================= NORTH INDIAN (32 dishes) =================
  {
    name: "Butter Chicken",
    nameHindi: "मक्खन चिकन",
    category: "north",
    servingSize: 100,
    calories: 240,
    protein: 16,
    carbs: 8,
    fat: 16,
    fiber: 1.2,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["high-protein", "rich", "curry"]
  },
  {
    name: "Dal Makhani",
    nameHindi: "दाल मखनी",
    category: "north",
    servingSize: 100,
    calories: 160,
    protein: 5.5,
    carbs: 18,
    fat: 7.5,
    fiber: 4.5,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["rich", "high-fiber", "vegetarian"]
  },
  {
    name: "Palak Paneer",
    nameHindi: "पालक पनीर",
    category: "north",
    servingSize: 100,
    calories: 145,
    protein: 7,
    carbs: 6,
    fat: 11,
    fiber: 2.5,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["low-carb", "vegetarian", "iron-rich"]
  },
  {
    name: "Rajma Masala",
    nameHindi: "राजमा मसाला",
    category: "north",
    servingSize: 100,
    calories: 120,
    protein: 4.8,
    carbs: 16,
    fat: 4,
    fiber: 3.8,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["vegetarian", "vegan", "high-fiber"]
  },
  {
    name: "Chole Masala",
    nameHindi: "छोले मसाला",
    category: "north",
    servingSize: 100,
    calories: 130,
    protein: 5,
    carbs: 18,
    fat: 4.5,
    fiber: 4.2,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["vegetarian", "vegan", "fiber-rich"]
  },
  {
    name: "Aloo Paratha",
    nameHindi: "आलू पराठा",
    category: "north",
    servingSize: 100,
    calories: 210,
    protein: 4.5,
    carbs: 32,
    fat: 7,
    fiber: 2.8,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["breakfast", "high-carb"]
  },
  {
    name: "Paneer Butter Masala",
    nameHindi: "पनीर बटर मसाला",
    category: "north",
    servingSize: 100,
    calories: 220,
    protein: 8.5,
    carbs: 9,
    fat: 17,
    fiber: 1.5,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["vegetarian", "rich", "paneer"]
  },
  {
    name: "Kadai Chicken",
    nameHindi: "कढ़ाई चिकन",
    category: "north",
    servingSize: 100,
    calories: 190,
    protein: 17.5,
    carbs: 4.5,
    fat: 11.5,
    fiber: 1.5,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["high-protein", "spicy"]
  },
  {
    name: "Shahi Paneer",
    nameHindi: "शाही पनीर",
    category: "north",
    servingSize: 100,
    calories: 230,
    protein: 8,
    carbs: 10,
    fat: 18,
    fiber: 1.3,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["rich", "sweetish", "vegetarian"]
  },
  {
    name: "Chicken Tikka Masala",
    nameHindi: "चिकन टिक्का मसाला",
    category: "north",
    servingSize: 100,
    calories: 210,
    protein: 15.5,
    carbs: 7.5,
    fat: 13,
    fiber: 1.2,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["high-protein", "curry"]
  },
  {
    name: "Malai Kofta",
    nameHindi: "मलाई कोफ्ता",
    category: "north",
    servingSize: 100,
    calories: 260,
    protein: 6,
    carbs: 16,
    fat: 20,
    fiber: 1.8,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["creamy", "festive", "vegetarian"]
  },
  {
    name: "Sarson Ka Saag",
    nameHindi: "सरसों का साग",
    category: "north",
    servingSize: 100,
    calories: 85,
    protein: 3,
    carbs: 7,
    fat: 5,
    fiber: 3.5,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["seasonal", "healthy", "iron-rich"]
  },
  {
    name: "Rogan Josh",
    nameHindi: "रोगन जोश",
    category: "north",
    servingSize: 100,
    calories: 220,
    protein: 18,
    carbs: 5,
    fat: 14,
    fiber: 1.1,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["high-protein", "mutton", "kashmiri"]
  },
  {
    name: "Chicken Korma",
    nameHindi: "चिकन कोरमा",
    category: "north",
    servingSize: 100,
    calories: 235,
    protein: 16,
    carbs: 6,
    fat: 16.5,
    fiber: 1.0,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["creamy", "rich", "meat"]
  },
  {
    name: "Methi Matar Malai",
    nameHindi: "मेथी मटर मलाई",
    category: "north",
    servingSize: 100,
    calories: 180,
    protein: 4.5,
    carbs: 11,
    fat: 13.5,
    fiber: 2.2,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["mild", "vegetarian", "fenugreek"]
  },
  {
    name: "Mutter Paneer",
    nameHindi: "मटर पनीर",
    category: "north",
    servingSize: 100,
    calories: 160,
    protein: 7.2,
    carbs: 9.8,
    fat: 10.2,
    fiber: 2.4,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["standard", "vegetarian", "paneer"]
  },
  {
    name: "Baingan Bharta (North Style)",
    nameHindi: "बैंगन भर्ता",
    category: "north",
    servingSize: 100,
    calories: 90,
    protein: 1.8,
    carbs: 7.5,
    fat: 5.8,
    fiber: 3.2,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["smoked", "low-calorie", "healthy"]
  },
  {
    name: "Kadhi Pakora",
    nameHindi: "कढ़ी पकोड़ा",
    category: "north",
    servingSize: 100,
    calories: 135,
    protein: 4.2,
    carbs: 13,
    fat: 7.5,
    fiber: 1.8,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["tangy", "yogurt-based", "comfort-food"]
  },
  {
    name: "Kashmiri Dum Aloo",
    nameHindi: "कश्मीरी दम आलू",
    category: "north",
    servingSize: 100,
    calories: 145,
    protein: 2.4,
    carbs: 18.5,
    fat: 7.0,
    fiber: 2.5,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["spicy", "potato", "kashmiri"]
  },
  {
    name: "Bhindi Do Pyaza",
    nameHindi: "भिंडी दो प्याजा",
    category: "north",
    servingSize: 100,
    calories: 110,
    protein: 2.0,
    carbs: 9.2,
    fat: 7.2,
    fiber: 2.8,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["okra", "onion", "dry-sabzi"]
  },
  {
    name: "Nihari",
    nameHindi: "निहारी",
    category: "north",
    servingSize: 100,
    calories: 250,
    protein: 19,
    carbs: 4.8,
    fat: 17.2,
    fiber: 1.1,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["traditional", "mutton", "slow-cooked"]
  },
  {
    name: "Paneer Tikka (Dry)",
    nameHindi: "पनीर टिक्का",
    category: "north",
    servingSize: 100,
    calories: 195,
    protein: 13.5,
    carbs: 5.5,
    fat: 13.2,
    fiber: 1.0,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["high-protein", "tandoor", "jain-friendly"]
  },
  {
    name: "Tandoori Chicken",
    nameHindi: "तंदूरी चिकन",
    category: "north",
    servingSize: 100,
    calories: 170,
    protein: 22,
    carbs: 2.5,
    fat: 8.0,
    fiber: 0.5,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["high-protein", "roasted", "low-carb"]
  },
  {
    name: "Chicken Seekh Kebab",
    nameHindi: "चिकन सीख कबाब",
    category: "north",
    servingSize: 100,
    calories: 185,
    protein: 19,
    carbs: 3.5,
    fat: 10.5,
    fiber: 0.8,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["high-protein", "grilled"]
  },
  {
    name: "Jeera Aloo",
    nameHindi: "जीरा आलू",
    category: "north",
    servingSize: 100,
    calories: 125,
    protein: 1.8,
    carbs: 16.5,
    fat: 5.8,
    fiber: 2.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["quick", "potato", "cumin"]
  },
  {
    name: "Mutton Korma",
    nameHindi: "मटन कोरमा",
    category: "north",
    servingSize: 100,
    calories: 275,
    protein: 18.5,
    carbs: 5.0,
    fat: 20.2,
    fiber: 0.9,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["rich", "festive", "meat"]
  },
  {
    name: "Paneer Pasanda",
    nameHindi: "पनीर पसंदा",
    category: "north",
    servingSize: 100,
    calories: 245,
    protein: 9.0,
    carbs: 10.5,
    fat: 18.8,
    fiber: 1.4,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["stuffed-paneer", "rich", "creamy"]
  },
  {
    name: "Mushroom Do Pyaza",
    nameHindi: "मशरूम दो प्याजा",
    category: "north",
    servingSize: 100,
    calories: 115,
    protein: 3.2,
    carbs: 8.5,
    fat: 7.5,
    fiber: 2.1,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["mushroom", "semi-dry", "vegetarian"]
  },
  {
    name: "Malai Chaap",
    nameHindi: "मलाई चाप",
    category: "north",
    servingSize: 100,
    calories: 220,
    protein: 9.5,
    carbs: 12.0,
    fat: 14.8,
    fiber: 1.5,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["soya", "tandoori", "creamy"]
  },
  {
    name: "Veg Kohlapuri",
    nameHindi: "वेज कोल्हापुरी",
    category: "north",
    servingSize: 100,
    calories: 155,
    protein: 3.5,
    carbs: 12.5,
    fat: 10.0,
    fiber: 3.0,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["spicy", "mixed-veg", "maharashtrian"]
  },
  {
    name: "Tandoori Soya Chaap (Dry)",
    nameHindi: "तंदूरी सोया चाप",
    category: "north",
    servingSize: 100,
    calories: 175,
    protein: 12.5,
    carbs: 11.0,
    fat: 8.8,
    fiber: 2.2,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["high-protein", "soya", "healthy-tandoor"]
  },
  {
    name: "Peshawari Chole",
    nameHindi: "पेशावरी छोले",
    category: "north",
    servingSize: 100,
    calories: 145,
    protein: 5.5,
    carbs: 19.0,
    fat: 5.2,
    fiber: 4.5,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["dark-chole", "spicy", "traditional"]
  },

  // ================= SOUTH INDIAN (25 dishes) =================
  {
    name: "Steamed Idli",
    nameHindi: "इडली",
    category: "south",
    servingSize: 100,
    calories: 115,
    protein: 3.0,
    carbs: 24.5,
    fat: 0.5,
    fiber: 1.8,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["breakfast", "steamed", "low-fat", "fermented"]
  },
  {
    name: "Plain Dosa",
    nameHindi: "सादा डोसा",
    category: "south",
    servingSize: 100,
    calories: 165,
    protein: 3.5,
    carbs: 29.5,
    fat: 3.5,
    fiber: 1.6,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["crispy", "breakfast", "fermented"]
  },
  {
    name: "Masala Dosa",
    nameHindi: "मसाला डोसा",
    category: "south",
    servingSize: 100,
    calories: 205,
    protein: 4.0,
    carbs: 34.0,
    fat: 5.8,
    fiber: 2.2,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["breakfast", "potato-stuffed", "popular"]
  },
  {
    name: "Medu Vada",
    nameHindi: "मेदू वड़ा",
    category: "south",
    servingSize: 100,
    calories: 240,
    protein: 6.5,
    carbs: 23.5,
    fat: 13.5,
    fiber: 3.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["fried", "lentil", "breakfast"]
  },
  {
    name: "Vegetable Sambar",
    nameHindi: "सांभर",
    category: "south",
    servingSize: 100,
    calories: 75,
    protein: 3.2,
    carbs: 11.5,
    fat: 1.8,
    fiber: 2.5,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["lentil-soup", "vegetables", "healthy"]
  },
  {
    name: "Tomato Rasam",
    nameHindi: "रसम",
    category: "south",
    servingSize: 100,
    calories: 45,
    protein: 1.2,
    carbs: 6.8,
    fat: 1.4,
    fiber: 1.1,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["soup", "digestive", "low-cal"]
  },
  {
    name: "Suji Upma",
    nameHindi: "उपमा",
    category: "south",
    servingSize: 100,
    calories: 140,
    protein: 3.2,
    carbs: 22.0,
    fat: 4.2,
    fiber: 1.9,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["semolina", "breakfast", "quick"]
  },
  {
    name: "Onion Uttapam",
    nameHindi: "उत्तपम",
    category: "south",
    servingSize: 100,
    calories: 180,
    protein: 4.2,
    carbs: 31.0,
    fat: 4.2,
    fiber: 2.0,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["savory-pancake", "breakfast"]
  },
  {
    name: "Coconut Appam",
    nameHindi: "अप्पम",
    category: "south",
    servingSize: 100,
    calories: 155,
    protein: 2.5,
    carbs: 28.0,
    fat: 3.5,
    fiber: 1.4,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["fermented-rice", "lacy", "breakfast"]
  },
  {
    name: "Puttu (Rice)",
    nameHindi: "पुट्टु",
    category: "south",
    servingSize: 100,
    calories: 195,
    protein: 3.8,
    carbs: 39.5,
    fat: 2.4,
    fiber: 2.1,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["steamed", "kerala", "coconut"]
  },
  {
    name: "Ven Pongal",
    nameHindi: "पोंगल",
    category: "south",
    servingSize: 100,
    calories: 185,
    protein: 4.5,
    carbs: 27.5,
    fat: 6.8,
    fiber: 2.0,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["ghee", "rice-lentil", "comfort-food"]
  },
  {
    name: "Pesarattu (Moong Dosa)",
    nameHindi: "पेसारट्टू",
    category: "south",
    servingSize: 100,
    calories: 170,
    protein: 8.5,
    carbs: 25.0,
    fat: 3.8,
    fiber: 3.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["high-protein", "green-gram", "andhra"]
  },
  {
    name: "Avial",
    nameHindi: "अवियल",
    category: "south",
    servingSize: 100,
    calories: 110,
    protein: 2.1,
    carbs: 8.5,
    fat: 7.8,
    fiber: 2.8,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["mixed-veg", "coconut", "kerala-traditional"]
  },
  {
    name: "Chicken Chettinad",
    nameHindi: "चेट्टिनाड चिकन",
    category: "south",
    servingSize: 100,
    calories: 200,
    protein: 18,
    carbs: 5.5,
    fat: 11.8,
    fiber: 1.6,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["spicy", "aromatic", "chettinad"]
  },
  {
    name: "Malabar Fish Curry",
    nameHindi: "मछली करी",
    category: "south",
    servingSize: 100,
    calories: 165,
    protein: 14.5,
    carbs: 4.8,
    fat: 10.0,
    fiber: 1.1,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["fish", "coconut-milk", "kerala"]
  },
  {
    name: "Coconut Chutney",
    nameHindi: "नारियल चटनी",
    category: "south",
    servingSize: 100,
    calories: 180,
    protein: 2.2,
    carbs: 8.0,
    fat: 15.5,
    fiber: 3.2,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["condiment", "raw-coconut", "side-dish"]
  },
  {
    name: "Tomato Onion Chutney",
    nameHindi: "टमाटर चटनी",
    category: "south",
    servingSize: 100,
    calories: 85,
    protein: 1.5,
    carbs: 8.8,
    fat: 5.0,
    fiber: 2.0,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["condiment", "spicy-tangy"]
  },
  {
    name: "Rava Dosa",
    nameHindi: "रवा डोसा",
    category: "south",
    servingSize: 100,
    calories: 175,
    protein: 3.8,
    carbs: 31.0,
    fat: 3.8,
    fiber: 1.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["semolina-crisp", "breakfast"]
  },
  {
    name: "Rava Khichdi (South Style)",
    nameHindi: "रवा खिचड़ी",
    category: "south",
    servingSize: 100,
    calories: 150,
    protein: 3.5,
    carbs: 23.0,
    fat: 5.0,
    fiber: 2.2,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["ghee-upma", "vegetables"]
  },
  {
    name: "Idiyappam (Nool Puttu)",
    nameHindi: "इडियाप्पम",
    category: "south",
    servingSize: 100,
    calories: 120,
    protein: 2.2,
    carbs: 27.0,
    fat: 0.4,
    fiber: 1.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["rice-noodles", "steamed", "light-breakfast"]
  },
  {
    name: "Kozhukattai (Sweet)",
    nameHindi: "कोझुकट्टई",
    category: "south",
    servingSize: 100,
    calories: 210,
    protein: 3.0,
    carbs: 41.0,
    fat: 3.8,
    fiber: 1.8,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["jaggery-coconut", "steamed-dumplings"]
  },
  {
    name: "Malabar Parotta",
    nameHindi: "केरल परोटा",
    category: "south",
    servingSize: 100,
    calories: 320,
    protein: 6.8,
    carbs: 48.0,
    fat: 11.2,
    fiber: 1.8,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["layered-bread", "maida"]
  },
  {
    name: "Kerala Egg Roast",
    nameHindi: "अंडा रोस्ट",
    category: "south",
    servingSize: 100,
    calories: 150,
    protein: 9.8,
    carbs: 6.2,
    fat: 9.5,
    fiber: 1.5,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["egg", "onion-gravy", "spicy"]
  },
  {
    name: "Beef Ularthiyathu (Kerala)",
    nameHindi: "बीफ रोस्ट",
    category: "south",
    servingSize: 100,
    calories: 240,
    protein: 23,
    carbs: 3.5,
    fat: 15.0,
    fiber: 1.4,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["high-protein", "beef", "dry-fry"]
  },
  {
    name: "Kozhi Curry (Kerala Chicken)",
    nameHindi: "कोझी करी",
    category: "south",
    servingSize: 100,
    calories: 185,
    protein: 16.5,
    carbs: 4.5,
    fat: 11.2,
    fiber: 1.5,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["coconut-base", "chicken-curry"]
  },

  // ================= STREET FOOD (21 dishes) =================
  {
    name: "Pani Puri (Puchka/GolGappa)",
    nameHindi: "पानी पूरी",
    category: "street_food",
    servingSize: 100,
    calories: 150,
    protein: 2.8,
    carbs: 26.5,
    fat: 3.8,
    fiber: 2.0,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["tangy-water", "mint", "famous"]
  },
  {
    name: "Bhel Puri",
    nameHindi: "भेल पूरी",
    category: "street_food",
    servingSize: 100,
    calories: 185,
    protein: 4.0,
    carbs: 32.5,
    fat: 4.5,
    fiber: 3.0,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["puffed-rice", "dry-snack", "tangy"]
  },
  {
    name: "Vada Pav",
    nameHindi: "वड़ा पाव",
    category: "street_food",
    servingSize: 100,
    calories: 270,
    protein: 5.5,
    carbs: 38.0,
    fat: 10.5,
    fiber: 2.8,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["mumbai-burger", "fried-potato", "spicy"]
  },
  {
    name: "Samosa",
    nameHindi: "समोसा",
    category: "street_food",
    servingSize: 100,
    calories: 260,
    protein: 4.2,
    carbs: 31.0,
    fat: 13.5,
    fiber: 2.2,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["deep-fried", "potato-filled"]
  },
  {
    name: "Samosa Chaat",
    nameHindi: "समोसा चाट",
    category: "street_food",
    servingSize: 100,
    calories: 220,
    protein: 4.8,
    carbs: 29.0,
    fat: 9.8,
    fiber: 3.2,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["yogurt-chutneys", "crushed-samosa"]
  },
  {
    name: "Kachori (Pyaaz)",
    nameHindi: "कचौड़ी",
    category: "street_food",
    servingSize: 100,
    calories: 310,
    protein: 5.0,
    carbs: 36.5,
    fat: 16.2,
    fiber: 2.4,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["fried-bread", "onion-stuffed"]
  },
  {
    name: "Aloo Tikki Chaat",
    nameHindi: "आलू टिक्की चाट",
    category: "street_food",
    servingSize: 100,
    calories: 190,
    protein: 3.5,
    carbs: 28.0,
    fat: 7.2,
    fiber: 2.9,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["potato-patties", "chutneys"]
  },
  {
    name: "Kutchi Dabeli",
    nameHindi: "दाबेली",
    category: "street_food",
    servingSize: 100,
    calories: 240,
    protein: 4.8,
    carbs: 36.0,
    fat: 8.5,
    fiber: 3.0,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["sweet-spicy", "peanut-crunch", "gujarat"]
  },
  {
    name: "Sev Puri",
    nameHindi: "सेव पूरी",
    category: "street_food",
    servingSize: 100,
    calories: 210,
    protein: 4.2,
    carbs: 31.0,
    fat: 7.8,
    fiber: 2.8,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["papdi-base", "potato-sev", "mumbai-street"]
  },
  {
    name: "Dahi Papdi Chaat",
    nameHindi: "पापड़ी चाट",
    category: "street_food",
    servingSize: 100,
    calories: 215,
    protein: 4.5,
    carbs: 29.5,
    fat: 9.0,
    fiber: 2.5,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["yogurt", "crisp-bread", "sweet-sour"]
  },
  {
    name: "Dahi Vada (Dahi Bhalla)",
    nameHindi: "दही वड़ा",
    category: "street_food",
    servingSize: 100,
    calories: 160,
    protein: 5.5,
    carbs: 18.0,
    fat: 7.2,
    fiber: 2.0,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["yogurt-soaked", "lentil-dumpling", "festive"]
  },
  {
    name: "Ragda Pattice",
    nameHindi: "रगड़ा पेटिस",
    category: "street_food",
    servingSize: 100,
    calories: 170,
    protein: 5.0,
    carbs: 29.0,
    fat: 3.8,
    fiber: 4.5,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["white-peas", "potato-patty", "fiber-rich"]
  },
  {
    name: "Misal Pav",
    nameHindi: "मिसल पाव",
    category: "street_food",
    servingSize: 100,
    calories: 245,
    protein: 7.5,
    carbs: 32.0,
    fat: 9.8,
    fiber: 4.0,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["spicy-sprout", "pav-bun", "maharashtrian"]
  },
  {
    name: "Mirchi Bajji (Stuffed)",
    nameHindi: "मिर्ची भज्जी",
    category: "street_food",
    servingSize: 100,
    calories: 220,
    protein: 3.8,
    carbs: 24.0,
    fat: 12.2,
    fiber: 2.5,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["chili-fritter", "deep-fried"]
  },
  {
    name: "Bread Pakora (Stuffed)",
    nameHindi: "ब्रेड पकोड़ा",
    category: "street_food",
    servingSize: 100,
    calories: 255,
    protein: 5.2,
    carbs: 30.5,
    fat: 12.5,
    fiber: 2.1,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["bread-potato", "batter-fried"]
  },
  {
    name: "Kathi Roll (Paneer)",
    nameHindi: "काठी रोल",
    category: "street_food",
    servingSize: 100,
    calories: 250,
    protein: 10.5,
    carbs: 29.0,
    fat: 10.2,
    fiber: 2.0,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["wrap", "paneer-filling", "street-roll"]
  },
  {
    name: "Chicken Shawarma (Wrap)",
    nameHindi: "शवर्मा",
    category: "street_food",
    servingSize: 100,
    calories: 210,
    protein: 14.0,
    carbs: 18.5,
    fat: 9.2,
    fiber: 1.5,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["grilled-chicken", "pita-wrap"]
  },
  {
    name: "Keema Pav (Mutton)",
    nameHindi: "कीमा पाव",
    category: "street_food",
    servingSize: 100,
    calories: 260,
    protein: 15.5,
    carbs: 22.0,
    fat: 12.8,
    fiber: 1.8,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["minced-meat", "pav-bread", "bombay-irani"]
  },
  {
    name: "Veg Steamed Momos",
    nameHindi: "मोमोज",
    category: "street_food",
    servingSize: 100,
    calories: 120,
    protein: 3.5,
    carbs: 24.5,
    fat: 0.8,
    fiber: 1.9,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["steamed-dumplings", "northeast"]
  },
  {
    name: "Aloo Chaat (Dry Spice)",
    nameHindi: "आलू चाट",
    category: "street_food",
    servingSize: 100,
    calories: 160,
    protein: 2.0,
    carbs: 26.0,
    fat: 5.5,
    fiber: 2.4,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["tangy-spicy", "potato-cube"]
  },
  {
    name: "Pav Bhaji (Street Style)",
    nameHindi: "पाव भाजी",
    category: "street_food",
    servingSize: 100,
    calories: 180,
    protein: 3.8,
    carbs: 26.2,
    fat: 6.8,
    fiber: 2.8,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["buttery", "popular", "mashed-veg"]
  },

  // ================= SWEETS (21 dishes) =================
  {
    name: "Gulab Jamun (2 pieces)",
    nameHindi: "गुलाब जामुन",
    category: "sweets",
    servingSize: 100,
    calories: 320,
    protein: 4.5,
    carbs: 58.0,
    fat: 7.8,
    fiber: 0.5,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["sugar-syrup", "fried-milk-solids", "festive"]
  },
  {
    name: "Rasgulla",
    nameHindi: "रसगुल्ला",
    category: "sweets",
    servingSize: 100,
    calories: 185,
    protein: 3.8,
    carbs: 38.5,
    fat: 1.8,
    fiber: 0.2,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["chena", "syrup-soaked", "bengali"]
  },
  {
    name: "Rice Kheer (Payasam)",
    nameHindi: "खीर",
    category: "sweets",
    servingSize: 100,
    calories: 140,
    protein: 3.5,
    carbs: 21.0,
    fat: 4.5,
    fiber: 0.4,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["milk-pudding", "rice", "sweet"]
  },
  {
    name: "Sooji Halwa (Sheera)",
    nameHindi: "सूजी हलवा",
    category: "sweets",
    servingSize: 100,
    calories: 285,
    protein: 3.8,
    carbs: 48.0,
    fat: 8.5,
    fiber: 1.2,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["semolina", "ghee", "prasad"]
  },
  {
    name: "Besan Ladoo",
    nameHindi: "बेसन लड्डू",
    category: "sweets",
    servingSize: 100,
    calories: 420,
    protein: 7.5,
    carbs: 52.0,
    fat: 20.5,
    fiber: 2.2,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["gram-flour", "ghee", "festive"]
  },
  {
    name: "Kaju Katli",
    nameHindi: "काजू कतली",
    category: "sweets",
    servingSize: 100,
    calories: 430,
    protein: 8.8,
    carbs: 51.0,
    fat: 21.5,
    fiber: 1.5,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["cashew", "fudge", "popular"]
  },
  {
    name: "Jalebi",
    nameHindi: "जलेबी",
    category: "sweets",
    servingSize: 100,
    calories: 345,
    protein: 2.2,
    carbs: 68.0,
    fat: 7.2,
    fiber: 0.6,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["fermented-batter", "fried", "syrup"]
  },
  {
    name: "Gajar Ka Halwa",
    nameHindi: "गाजर हलवा",
    category: "sweets",
    servingSize: 100,
    calories: 200,
    protein: 3.2,
    carbs: 27.5,
    fat: 8.8,
    fiber: 2.0,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["carrot", "winter-sweet", "khoya"]
  },
  {
    name: "Rasmalai",
    nameHindi: "रसमलाई",
    category: "sweets",
    servingSize: 100,
    calories: 220,
    protein: 6.8,
    carbs: 24.5,
    fat: 10.5,
    fiber: 0.3,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["chena", "saffron-milk", "bengali-sweet"]
  },
  {
    name: "Mysore Pak (Ghee)",
    nameHindi: "मैसूर पाक",
    category: "sweets",
    servingSize: 100,
    calories: 495,
    protein: 4.8,
    carbs: 54.0,
    fat: 28.5,
    fiber: 1.0,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["rich", "south-sweet", "gram-flour"]
  },
  {
    name: "Modak (Steamed/Ukadiche)",
    nameHindi: "मोदक",
    category: "sweets",
    servingSize: 100,
    calories: 195,
    protein: 2.8,
    carbs: 38.0,
    fat: 3.2,
    fiber: 2.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["steamed", "ganesh-festival", "coconut-jaggery"]
  },
  {
    name: "Elaneer Payasam",
    nameHindi: "पायसम",
    category: "sweets",
    servingSize: 100,
    calories: 125,
    protein: 1.8,
    carbs: 16.2,
    fat: 6.2,
    fiber: 0.8,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["tender-coconut", "south-sweet", "milk"]
  },
  {
    name: "Elaichi Shrikhand",
    nameHindi: "श्रीखंड",
    category: "sweets",
    servingSize: 100,
    calories: 260,
    protein: 5.8,
    carbs: 42.0,
    fat: 7.8,
    fiber: 0.2,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["hung-curd", "cardamom", "west-sweet"]
  },
  {
    name: "Sandesh (Plain Nolen Gur)",
    nameHindi: "सन्देश",
    category: "sweets",
    servingSize: 100,
    calories: 190,
    protein: 7.2,
    carbs: 24.0,
    fat: 7.2,
    fiber: 0.1,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["chena-fudge", "bengali-sweet"]
  },
  {
    name: "Malpua (Syrup)",
    nameHindi: "मालपुआ",
    category: "sweets",
    servingSize: 100,
    calories: 340,
    protein: 3.5,
    carbs: 58.0,
    fat: 10.5,
    fiber: 0.8,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["fried-pancake", "heavy", "festive"]
  },
  {
    name: "Rabri (Plain)",
    nameHindi: "राबड़ी",
    category: "sweets",
    servingSize: 100,
    calories: 275,
    protein: 8.5,
    carbs: 31.0,
    fat: 13.0,
    fiber: 0.2,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["reduced-milk", "creamy"]
  },
  {
    name: "Motichoor Ladoo",
    nameHindi: "मोतीचूर लड्डू",
    category: "sweets",
    servingSize: 100,
    calories: 385,
    protein: 4.2,
    carbs: 58.0,
    fat: 15.0,
    fiber: 1.0,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["tiny-boondi", "ghee", "festive-classic"]
  },
  {
    name: "Kaju Roll",
    nameHindi: "काजू रोल",
    category: "sweets",
    servingSize: 100,
    calories: 440,
    protein: 9.0,
    carbs: 49.5,
    fat: 22.8,
    fiber: 1.4,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["cashew-pistachio", "luxury-sweet"]
  },
  {
    name: "Puran Poli",
    nameHindi: "पूरन पोली",
    category: "sweets",
    servingSize: 100,
    calories: 290,
    protein: 6.2,
    carbs: 54.0,
    fat: 5.5,
    fiber: 3.2,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["stuffed-bread", "jaggery-chana", "maharashtra"]
  },
  {
    name: "Double Ka Meetha",
    nameHindi: "डबल का मीठा",
    category: "sweets",
    servingSize: 100,
    calories: 310,
    protein: 4.8,
    carbs: 49.0,
    fat: 10.5,
    fiber: 1.2,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["bread-pudding", "hyderabad", "festive"]
  },
  {
    name: "Coconut Ladoo",
    nameHindi: "नारियल लड्डू",
    category: "sweets",
    servingSize: 100,
    calories: 360,
    protein: 4.5,
    carbs: 46.0,
    fat: 17.5,
    fiber: 3.8,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["coconut", "condensed-milk", "quick-sweet"]
  },

  // ================= BEVERAGES (16 dishes) =================
  {
    name: "Sweet Lassi",
    nameHindi: "मीठी लस्सी",
    category: "beverages",
    servingSize: 100,
    calories: 95,
    protein: 2.2,
    carbs: 14.5,
    fat: 3.0,
    fiber: 0.0,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["sweet", "yogurt-drink", "cooling"]
  },
  {
    name: "Mango Lassi",
    nameHindi: "मैंगो लस्सी",
    category: "beverages",
    servingSize: 100,
    calories: 110,
    protein: 2.1,
    carbs: 18.0,
    fat: 3.2,
    fiber: 0.6,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["mango", "yogurt-drink", "thick"]
  },
  {
    name: "Masala Chai (with Milk & Sugar)",
    nameHindi: "मसाला चाय",
    category: "beverages",
    servingSize: 100,
    calories: 45,
    protein: 1.1,
    carbs: 7.2,
    fat: 1.2,
    fiber: 0.1,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["tea", "spiced", "hot-drink"]
  },
  {
    name: "Ginger Chai (Adrak)",
    nameHindi: "अदरक चाय",
    category: "beverages",
    servingSize: 100,
    calories: 40,
    protein: 1.0,
    carbs: 6.8,
    fat: 1.0,
    fiber: 0.2,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["ginger-tea", "herbal-notes"]
  },
  {
    name: "Salted Buttermilk (Chaas)",
    nameHindi: "छाछ",
    category: "beverages",
    servingSize: 100,
    calories: 30,
    protein: 1.2,
    carbs: 3.5,
    fat: 1.0,
    fiber: 0.0,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["salty", "low-calorie", "digestive"]
  },
  {
    name: "Masala Buttermilk (Spiced Chaas)",
    nameHindi: "मसाला छाछ",
    category: "beverages",
    servingSize: 100,
    calories: 32,
    protein: 1.2,
    carbs: 3.8,
    fat: 1.0,
    fiber: 0.2,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["spiced-buttermilk", "refreshing", "low-cal"]
  },
  {
    name: "Nimbu Pani (Sweet & Salty Shahi Shabat)",
    nameHindi: "शिकंजी / नींबू पानी",
    category: "beverages",
    servingSize: 100,
    calories: 35,
    protein: 0.1,
    carbs: 8.8,
    fat: 0.0,
    fiber: 0.1,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["lemonade", "refreshing", "summer"]
  },
  {
    name: "Thandai (Rich)",
    nameHindi: "ठंडाई",
    category: "beverages",
    servingSize: 100,
    calories: 130,
    protein: 3.5,
    carbs: 16.5,
    fat: 5.8,
    fiber: 0.8,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["almonds-seeds", "holi-drink", "spiced-milk"]
  },
  {
    name: "Masala Milk (Kesar Badam)",
    nameHindi: "मसाला दूध",
    category: "beverages",
    servingSize: 100,
    calories: 120,
    protein: 3.8,
    carbs: 14.0,
    fat: 5.5,
    fiber: 0.6,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["saffron", "almond-slivers", "warm-drink"]
  },
  {
    name: "Jaljeera (Water Based)",
    nameHindi: "जलजीरा",
    category: "beverages",
    servingSize: 100,
    calories: 15,
    protein: 0.2,
    carbs: 3.5,
    fat: 0.1,
    fiber: 0.4,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["tangy-spice", "digestive-aid", "zero-fat"]
  },
  {
    name: "South Indian Filter Coffee",
    nameHindi: "फ़िल्टर कॉफ़ी",
    category: "beverages",
    servingSize: 100,
    calories: 60,
    protein: 1.5,
    carbs: 8.0,
    fat: 2.2,
    fiber: 0.0,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["coffee", "hot-drink", "milky"]
  },
  {
    name: "Solkadhi",
    nameHindi: "सोलकढ़ी",
    category: "beverages",
    servingSize: 100,
    calories: 65,
    protein: 0.8,
    carbs: 4.2,
    fat: 5.0,
    fiber: 0.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["kokum-fruit", "coconut-milk", "konkan-cuisine"]
  },
  {
    name: "Sugarcane Juice (Raw)",
    nameHindi: "गन्ने का रस",
    category: "beverages",
    servingSize: 100,
    calories: 78,
    protein: 0.2,
    carbs: 19.0,
    fat: 0.1,
    fiber: 0.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["sugarcane", "raw-energy", "hydrating"]
  },
  {
    name: "Tender Coconut Water",
    nameHindi: "नारियल पानी",
    category: "beverages",
    servingSize: 100,
    calories: 19,
    protein: 0.7,
    carbs: 3.7,
    fat: 0.2,
    fiber: 1.1,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["natural-electrolyte", "hydrating", "low-cal"]
  },
  {
    name: "Aam Panna",
    nameHindi: "आम पन्ना",
    category: "beverages",
    servingSize: 100,
    calories: 55,
    protein: 0.3,
    carbs: 13.5,
    fat: 0.1,
    fiber: 0.6,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["raw-mango", "sweet-sour", "anti-heat"]
  },
  {
    name: "Solkadhi (Spiced)",
    nameHindi: "सोलकढ़ी मसाला",
    category: "beverages",
    servingSize: 100,
    calories: 70,
    protein: 0.8,
    carbs: 4.5,
    fat: 5.2,
    fiber: 0.5,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["spiced-kokum", "cooling-digestive"]
  },

  // ================= RICE (15 dishes) =================
  {
    name: "Vegetable Biryani",
    nameHindi: "वेज बिरयानी",
    category: "rice",
    servingSize: 100,
    calories: 145,
    protein: 3.2,
    carbs: 26.5,
    fat: 2.8,
    fiber: 2.2,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["spiced-rice", "mixed-veg", "main-course"]
  },
  {
    name: "Chicken Biryani (Hyderabadi)",
    nameHindi: "चिकन बिरयानी",
    category: "rice",
    servingSize: 100,
    calories: 190,
    protein: 11.5,
    carbs: 23.0,
    fat: 5.8,
    fiber: 1.2,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["spiced-rice", "chicken", "iconic-dish"]
  },
  {
    name: "Mutton Biryani",
    nameHindi: "मटन बिरयानी",
    category: "rice",
    servingSize: 100,
    calories: 215,
    protein: 12.0,
    carbs: 22.5,
    fat: 8.5,
    fiber: 1.2,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["rich-biryani", "mutton", "festive"]
  },
  {
    name: "Egg Biryani",
    nameHindi: "अंडा बिरयानी",
    category: "rice",
    servingSize: 100,
    calories: 165,
    protein: 6.8,
    carbs: 24.0,
    fat: 4.5,
    fiber: 1.4,
    isVegetarian: false,
    isVegan: false,
    isJain: false,
    tags: ["boiled-egg", "spiced-rice"]
  },
  {
    name: "Moong Dal Khichdi",
    nameHindi: "खिचड़ी",
    category: "rice",
    servingSize: 100,
    calories: 110,
    protein: 3.5,
    carbs: 21.0,
    fat: 1.5,
    fiber: 2.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["comfort-food", "digestive", "lentil-rice"]
  },
  {
    name: "Curd Rice (Dahi Chawal)",
    nameHindi: "दही चावल",
    category: "rice",
    servingSize: 100,
    calories: 115,
    protein: 3.2,
    carbs: 18.5,
    fat: 3.0,
    fiber: 1.0,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["cooling", "tempered", "digestive"]
  },
  {
    name: "Lemon Rice",
    nameHindi: "लेमन राइस",
    category: "rice",
    servingSize: 100,
    calories: 135,
    protein: 2.5,
    carbs: 26.0,
    fat: 2.2,
    fiber: 1.4,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["tempered-lemon", "yellow-rice"]
  },
  {
    name: "Jeera Rice",
    nameHindi: "जीरा चावल",
    category: "rice",
    servingSize: 100,
    calories: 130,
    protein: 2.2,
    carbs: 25.5,
    fat: 2.0,
    fiber: 1.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["cumin-scented", "basmati"]
  },
  {
    name: "Tomato Rice (Thakkali Sadam)",
    nameHindi: "टमाटर चावल",
    category: "rice",
    servingSize: 100,
    calories: 125,
    protein: 2.4,
    carbs: 24.5,
    fat: 1.8,
    fiber: 1.6,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["tangy-rice", "tempered"]
  },
  {
    name: "Coconut Rice (South Style)",
    nameHindi: "नारियल चावल",
    category: "rice",
    servingSize: 100,
    calories: 165,
    protein: 2.8,
    carbs: 25.0,
    fat: 5.8,
    fiber: 2.1,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["grated-coconut", "mild-sweet"]
  },
  {
    name: "Ghee Rice",
    nameHindi: "घी चावल",
    category: "rice",
    servingSize: 100,
    calories: 160,
    protein: 2.4,
    carbs: 25.0,
    fat: 5.5,
    fiber: 1.0,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["buttery", "aromatic", "kerala-style"]
  },
  {
    name: "Schezwan Fried Rice (Indo-Chinese)",
    nameHindi: "फ्राइड राइस",
    category: "rice",
    servingSize: 100,
    calories: 155,
    protein: 3.0,
    carbs: 28.0,
    fat: 3.2,
    fiber: 1.8,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["spicy-chinese", "wok-fried"]
  },
  {
    name: "Kashmiri Pulao (Fruity)",
    nameHindi: "कश्मीरी पुलाव",
    category: "rice",
    servingSize: 100,
    calories: 150,
    protein: 2.8,
    carbs: 28.0,
    fat: 2.8,
    fiber: 1.8,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["nuts-raisins", "sweet-savory", "basmati"]
  },
  {
    name: "Tamarind Rice (Puliyodharai)",
    nameHindi: "इमली चावल",
    category: "rice",
    servingSize: 100,
    calories: 145,
    protein: 2.6,
    carbs: 27.5,
    fat: 2.5,
    fiber: 1.9,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["tangy-tamarind", "spiced-powder"]
  },
  {
    name: "Plain Basmati Rice (Boiled)",
    nameHindi: "उबले चावल",
    category: "rice",
    servingSize: 100,
    calories: 110,
    protein: 2.2,
    carbs: 24.5,
    fat: 0.2,
    fiber: 0.8,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["plain-rice", "boiled"]
  },

  // ================= DAL (10 dishes) =================
  {
    name: "Dal Tadka (Yellow Arhar)",
    nameHindi: "दाल तड़का",
    category: "dal",
    servingSize: 100,
    calories: 105,
    protein: 4.8,
    carbs: 14.5,
    fat: 3.2,
    fiber: 3.2,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["yellow-lentil", "tempered-garlic", "standard"]
  },
  {
    name: "Dal Fry (Rich)",
    nameHindi: "दाल फ्राई",
    category: "dal",
    servingSize: 100,
    calories: 120,
    protein: 4.8,
    carbs: 15.0,
    fat: 4.5,
    fiber: 3.0,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["onions-tomatoes", "vegetarian"]
  },
  {
    name: "Moong Dal Tadka (Light)",
    nameHindi: "मूंग दाल तड़का",
    category: "dal",
    servingSize: 100,
    calories: 90,
    protein: 5.0,
    carbs: 13.5,
    fat: 2.0,
    fiber: 3.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["light-lentil", "easy-digest", "low-cal"]
  },
  {
    name: "Chana Dal (Bengal Gram)",
    nameHindi: "चना दाल",
    category: "dal",
    servingSize: 100,
    calories: 115,
    protein: 5.5,
    carbs: 17.5,
    fat: 2.8,
    fiber: 4.2,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["thick-lentil", "high-protein", "fiber-rich"]
  },
  {
    name: "Masoor Dal (Red Lentil)",
    nameHindi: "मसूर दाल",
    category: "dal",
    servingSize: 100,
    calories: 95,
    protein: 5.2,
    carbs: 14.8,
    fat: 1.8,
    fiber: 3.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["quick-cook", "healthy-lentil"]
  },
  {
    name: "Panchmel Dal (Rajasthani)",
    nameHindi: "पंचमेल दाल",
    category: "dal",
    servingSize: 100,
    calories: 125,
    protein: 6.0,
    carbs: 17.0,
    fat: 3.8,
    fiber: 4.8,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["five-lentils", "rajasthani", "high-fiber"]
  },
  {
    name: "Dal Bukhara (Whole Urad)",
    nameHindi: "दाल बुखारा",
    category: "dal",
    servingSize: 100,
    calories: 155,
    protein: 5.8,
    carbs: 16.5,
    fat: 7.2,
    fiber: 4.6,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["slow-cooked", "black-urad", "creamy"]
  },
  {
    name: "Dal Maharani",
    nameHindi: "दाल महारानी",
    category: "dal",
    servingSize: 100,
    calories: 140,
    protein: 5.2,
    carbs: 16.0,
    fat: 6.0,
    fiber: 4.0,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["kidney-beans-urad", "creamy-dal"]
  },
  {
    name: "Kulthi Dal (Horse Gram)",
    nameHindi: "कुलथी दाल",
    category: "dal",
    servingSize: 100,
    calories: 110,
    protein: 6.8,
    carbs: 18.0,
    fat: 1.5,
    fiber: 5.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["horsegram", "high-fiber", "medicinal-notes"]
  },
  {
    name: "Black Urad Dal (Plain)",
    nameHindi: "काली दाल",
    category: "dal",
    servingSize: 100,
    calories: 110,
    protein: 5.0,
    carbs: 16.5,
    fat: 2.2,
    fiber: 4.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["black-urad", "fiber-rich"]
  },

  // ================= SABZI (15 dishes) =================
  {
    name: "Aloo Gobi (Dry)",
    nameHindi: "आलू गोभी",
    category: "sabzi",
    servingSize: 100,
    calories: 115,
    protein: 2.2,
    carbs: 14.5,
    fat: 5.8,
    fiber: 2.8,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["potato-cauliflower", "standard-dry-sabzi"]
  },
  {
    name: "Bhindi Masala (Dry)",
    nameHindi: "भिंडी मसाला",
    category: "sabzi",
    servingSize: 100,
    calories: 105,
    protein: 1.9,
    carbs: 9.8,
    fat: 6.8,
    fiber: 3.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["okra", "low-cal", "vegetarian"]
  },
  {
    name: "Gobi Gajar Matar",
    nameHindi: "गोभी गाजर मटर",
    category: "sabzi",
    servingSize: 100,
    calories: 95,
    protein: 2.1,
    carbs: 11.2,
    fat: 4.8,
    fiber: 3.2,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["mixed-vegetables", "winter-special", "healthy"]
  },
  {
    name: "Lauki Ki Sabzi (Ghiya)",
    nameHindi: "लौकी की सब्जी",
    category: "sabzi",
    servingSize: 100,
    calories: 60,
    protein: 0.8,
    carbs: 5.2,
    fat: 4.2,
    fiber: 2.2,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["bottlegourd", "low-calorie", "digestive-aid"]
  },
  {
    name: "Torai Ki Sabzi",
    nameHindi: "तुरई की सब्जी",
    category: "sabzi",
    servingSize: 100,
    calories: 55,
    protein: 0.9,
    carbs: 4.8,
    fat: 3.8,
    fiber: 2.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["spongegourd", "low-calorie", "diet-friendly"]
  },
  {
    name: "Karela Bittergourd Fry",
    nameHindi: "करेला फ्राई",
    category: "sabzi",
    servingSize: 100,
    calories: 120,
    protein: 2.0,
    carbs: 10.5,
    fat: 8.2,
    fiber: 3.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["bittergourd", "healthy-bitter", "low-glycemic"]
  },
  {
    name: "Cabbage Thoran (South)",
    nameHindi: "पत्तागोभी थोरन",
    category: "sabzi",
    servingSize: 100,
    calories: 85,
    protein: 1.8,
    carbs: 7.2,
    fat: 5.8,
    fiber: 2.5,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["cabbage-coconut", "kerala-side"]
  },
  {
    name: "Aloo Baingan (Dry)",
    nameHindi: "आलू बैंगन",
    category: "sabzi",
    servingSize: 100,
    calories: 110,
    protein: 1.8,
    carbs: 13.5,
    fat: 5.5,
    fiber: 2.8,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["potato-eggplant", "standard-lunch"]
  },
  {
    name: "Capsicum Masala",
    nameHindi: "शिमला मिर्च मसाला",
    category: "sabzi",
    servingSize: 100,
    calories: 95,
    protein: 2.0,
    carbs: 8.8,
    fat: 6.2,
    fiber: 2.2,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["bell-pepper", "peanut-paste"]
  },
  {
    name: "Paneer Bhurji",
    nameHindi: "पनीर भुर्जी",
    category: "sabzi",
    servingSize: 100,
    calories: 210,
    protein: 12.8,
    carbs: 5.5,
    fat: 15.5,
    fiber: 1.2,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["scrambled-paneer", "high-protein", "vegetarian"]
  },
  {
    name: "Mixed Vegetable Curry",
    nameHindi: "मिक्स वेज",
    category: "sabzi",
    servingSize: 100,
    calories: 130,
    protein: 2.8,
    carbs: 11.8,
    fat: 8.0,
    fiber: 3.5,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["gravy-veg", "mixed-greens-beans"]
  },
  {
    name: "Bharwan Bhindi (Stuffed Okra)",
    nameHindi: "भरवां भिंडी",
    category: "sabzi",
    servingSize: 100,
    calories: 125,
    protein: 2.2,
    carbs: 11.0,
    fat: 8.5,
    fiber: 3.2,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["stuffed-spices", "dry-okra"]
  },
  {
    name: "Bharwan Baingan",
    nameHindi: "भरवां बैंगन",
    category: "sabzi",
    servingSize: 100,
    calories: 130,
    protein: 2.0,
    carbs: 12.0,
    fat: 8.8,
    fiber: 3.4,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["stuffed-eggplant", "spicy-gravy"]
  },
  {
    name: "Lauki Kofta Curry",
    nameHindi: "लौकी कोफ्ता",
    category: "sabzi",
    servingSize: 100,
    calories: 160,
    protein: 3.5,
    carbs: 14.0,
    fat: 10.2,
    fiber: 2.4,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["fried-kofta-balls", "onion-gravy"]
  },
  {
    name: "Sem Aloo (Flat Beans & Potato)",
    nameHindi: "सेम आलू",
    category: "sabzi",
    servingSize: 100,
    calories: 105,
    protein: 2.4,
    carbs: 13.8,
    fat: 4.8,
    fiber: 3.2,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["broad-flat-beans", "homestyle-dry"]
  },

  // ================= BREADS (11 dishes) =================
  {
    name: "Plain Roti (Whole Wheat Phulka)",
    nameHindi: "रोटी / फुल्का",
    category: "breads",
    servingSize: 100,
    calories: 260,
    protein: 9.0,
    carbs: 52.0,
    fat: 1.5,
    fiber: 6.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["whole-wheat", "flatbread", "staple"]
  },
  {
    name: "Tandoori Roti (Plain)",
    nameHindi: "तंदूरी रोटी",
    category: "breads",
    servingSize: 100,
    calories: 245,
    protein: 8.5,
    carbs: 49.5,
    fat: 1.2,
    fiber: 6.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["clay-oven", "whole-wheat", "chewy"]
  },
  {
    name: "Plain Paratha (Triangle Tawa)",
    nameHindi: "सादा पराठा",
    category: "breads",
    servingSize: 100,
    calories: 320,
    protein: 7.2,
    carbs: 48.0,
    fat: 11.5,
    fiber: 5.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["pan-fried", "layered-bread"]
  },
  {
    name: "Garlic Naan (Clay Oven)",
    nameHindi: "लहसुन नान",
    category: "breads",
    servingSize: 100,
    calories: 295,
    protein: 7.8,
    carbs: 54.0,
    fat: 5.5,
    fiber: 2.2,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["yeast-bread", "refined-flour", "buttery"]
  },
  {
    name: "Plain Poori",
    nameHindi: "पूरी",
    category: "breads",
    servingSize: 100,
    calories: 345,
    protein: 7.5,
    carbs: 49.0,
    fat: 13.5,
    fiber: 5.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["deep-fried", "wheat-puff"]
  },
  {
    name: "Bhatura (Yeast Fried)",
    nameHindi: "भटूरा",
    category: "breads",
    servingSize: 100,
    calories: 380,
    protein: 7.2,
    carbs: 51.0,
    fat: 16.5,
    fiber: 1.8,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["maida-flour", "deep-fried", "rich"]
  },
  {
    name: "Missi Roti (Gram Flour Mix)",
    nameHindi: "मिस्सी रोटी",
    category: "breads",
    servingSize: 100,
    calories: 275,
    protein: 11.2,
    carbs: 46.5,
    fat: 4.8,
    fiber: 5.8,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["high-protein", "besan", "healthy-bread"]
  },
  {
    name: "Gujarati Methi Thepla",
    nameHindi: "थेपला",
    category: "breads",
    servingSize: 100,
    calories: 290,
    protein: 8.5,
    carbs: 47.0,
    fat: 7.8,
    fiber: 4.5,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["fenugreek", "spiced-flatbread", "travel-friendly"]
  },
  {
    name: "Amritsari Kulcha (Stuffed)",
    nameHindi: "अमृतसरी कुलचा",
    category: "breads",
    servingSize: 100,
    calories: 280,
    protein: 6.8,
    carbs: 49.0,
    fat: 6.5,
    fiber: 2.5,
    isVegetarian: true,
    isVegan: false,
    isJain: false,
    tags: ["potato-stuffed", "clay-oven", "buttery"]
  },
  {
    name: "Rumali Roti",
    nameHindi: "रुमाली रोटी",
    category: "breads",
    servingSize: 100,
    calories: 250,
    protein: 7.5,
    carbs: 52.0,
    fat: 1.2,
    fiber: 2.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["thin-hand-tossed", "refined-flour"]
  },
  {
    name: "Bajra Roti (Pearl Millet)",
    nameHindi: "बाजरा रोटी",
    category: "breads",
    servingSize: 100,
    calories: 280,
    protein: 9.8,
    carbs: 56.5,
    fat: 2.2,
    fiber: 7.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["millet-bread", "gluten-free", "winter-staple"]
  },

  // ================= SNACKS (20 dishes) =================
  {
    name: "Khaman Dhokla",
    nameHindi: "ढोकला",
    category: "snacks",
    servingSize: 100,
    calories: 150,
    protein: 6.2,
    carbs: 22.0,
    fat: 4.2,
    fiber: 1.8,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["steamed", "fermented-chana", "gujarati", "low-fat"]
  },
  {
    name: "Kanda Poha (Flat Rice)",
    nameHindi: "पोहा",
    category: "snacks",
    servingSize: 100,
    calories: 175,
    protein: 3.5,
    carbs: 32.5,
    fat: 3.5,
    fiber: 1.8,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["flattened-rice", "onion-peanut", "breakfast"]
  },
  {
    name: "Mixed Sprouts Salad",
    nameHindi: "स्प्राउट्स सलाद",
    category: "snacks",
    servingSize: 100,
    calories: 90,
    protein: 7.0,
    carbs: 13.5,
    fat: 0.8,
    fiber: 3.8,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["diet-friendly", "raw", "high-protein", "jain-friendly"]
  },
  {
    name: "Roasted Chana (With Skin)",
    nameHindi: "भुना चना",
    category: "snacks",
    servingSize: 100,
    calories: 360,
    protein: 18.5,
    carbs: 58.0,
    fat: 5.2,
    fiber: 12.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["super-high-protein", "fiber-superfoods", "roasted"]
  },
  {
    name: "Namkeen Mathri (Deep Fried)",
    nameHindi: "मठरी",
    category: "snacks",
    servingSize: 100,
    calories: 460,
    protein: 7.8,
    carbs: 54.0,
    fat: 24.2,
    fiber: 1.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["dry-snack", "fried", "tea-partner"]
  },
  {
    name: "South Indian Murukku",
    nameHindi: "मुरुक्कु",
    category: "snacks",
    servingSize: 100,
    calories: 475,
    protein: 6.8,
    carbs: 56.0,
    fat: 25.0,
    fiber: 2.1,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["rice-gram-flour", "fried-coil", "crunchy"]
  },
  {
    name: "Kerala Banana Chips (Coconut Oil)",
    nameHindi: "केला चिप्स",
    category: "snacks",
    servingSize: 100,
    calories: 510,
    protein: 2.2,
    carbs: 58.0,
    fat: 30.0,
    fiber: 3.8,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["banana", "deep-fried-oil", "crisp"]
  },
  {
    name: "Sabudana Khichdi",
    nameHindi: "साबूदाना खिचड़ी",
    category: "snacks",
    servingSize: 100,
    calories: 220,
    protein: 1.8,
    carbs: 46.0,
    fat: 3.5,
    fiber: 1.2,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["tapioca-pearls", "fasting-food", "peanut"]
  },
  {
    name: "Sabudana Vada (Deep Fried)",
    nameHindi: "साबूदाना वड़ा",
    category: "snacks",
    servingSize: 100,
    calories: 310,
    protein: 2.2,
    carbs: 44.5,
    fat: 14.2,
    fiber: 1.4,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["fried-patty", "fasting-snack"]
  },
  {
    name: "Khandvi (Rolls)",
    nameHindi: "खांडवी",
    category: "snacks",
    servingSize: 100,
    calories: 145,
    protein: 5.5,
    carbs: 17.5,
    fat: 6.2,
    fiber: 1.6,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["steamed-gram", "tempered-mustard", "gujarat"]
  },
  {
    name: "Onion Pakora (Kanda Bhaji)",
    nameHindi: "प्याज पकोड़ा",
    category: "snacks",
    servingSize: 100,
    calories: 290,
    protein: 5.0,
    carbs: 26.0,
    fat: 18.5,
    fiber: 2.2,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["fried-fritters", "rainy-day"]
  },
  {
    name: "Dry Fruit Almond & Cashew Mix",
    nameHindi: "मेवा मिक्स",
    category: "snacks",
    servingSize: 100,
    calories: 580,
    protein: 18,
    carbs: 22.0,
    fat: 48.0,
    fiber: 6.8,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["healthy-fats", "high-protein", "raw-nuts"]
  },
  {
    name: "Roasted Makhana (Fox Nuts)",
    nameHindi: "भुना मखाना",
    category: "snacks",
    servingSize: 100,
    calories: 180,
    protein: 4.8,
    carbs: 38.0,
    fat: 1.2,
    fiber: 3.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["low-calorie", "healthy-crunch", "fasting"]
  },
  {
    name: "Masala Peanuts (Air Fried)",
    nameHindi: "मसाला मूंगफली",
    category: "snacks",
    servingSize: 100,
    calories: 450,
    protein: 19.5,
    carbs: 21.0,
    fat: 32.0,
    fiber: 6.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["high-protein", "peanuts", "crunchy"]
  },
  {
    name: "Haldiram Aloo Bhujia",
    nameHindi: "आलू भुजिया",
    category: "snacks",
    servingSize: 100,
    calories: 560,
    protein: 9.0,
    carbs: 42.0,
    fat: 39.5,
    fiber: 2.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["crisp-namkeen", "processed-snack"]
  },
  {
    name: "Chakli (Baked)",
    nameHindi: "चकली",
    category: "snacks",
    servingSize: 100,
    calories: 360,
    protein: 7.2,
    carbs: 62.0,
    fat: 8.8,
    fiber: 3.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["baked-healthy", "savory-crunch"]
  },
  {
    name: "Roasted Salted Cashews",
    nameHindi: "काजू नमकीन",
    category: "snacks",
    servingSize: 100,
    calories: 590,
    protein: 17.5,
    carbs: 28.5,
    fat: 46.8,
    fiber: 3.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["cashews", "salted", "nuts"]
  },
  {
    name: "Gujarati Khakhra (Plain)",
    nameHindi: "खाखरा",
    category: "snacks",
    servingSize: 100,
    calories: 320,
    protein: 8.8,
    carbs: 61.5,
    fat: 4.5,
    fiber: 5.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["crispy-roti", "low-fat-snack", "travel"]
  },
  {
    name: "Ragi Malt (Sugar Free)",
    nameHindi: "रागी माल्ट",
    category: "snacks",
    servingSize: 100,
    calories: 90,
    protein: 2.5,
    carbs: 18.0,
    fat: 0.8,
    fiber: 3.2,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["finger-millet", "fiber-superfoods", "calcium-rich"]
  },
  {
    name: "Roasted Peanuts (Plain)",
    nameHindi: "भुनी मूंगफली",
    category: "snacks",
    servingSize: 100,
    calories: 565,
    protein: 25.8,
    carbs: 16.0,
    fat: 49.0,
    fiber: 8.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["nuts", "super-high-protein", "raw-energy"]
  },
  // ================= INDIAN PICKLES (AACHAR) =================
  {
    name: "Mango Pickle (Aam ka Aachar)",
    nameHindi: "आम का अचार",
    category: "snacks",
    servingSize: 10,
    calories: 30,
    protein: 0.2,
    carbs: 1.0,
    fat: 2.8,
    fiber: 0.3,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["pickle", "aachar", "accompaniment"]
  },
  {
    name: "Lemon Pickle (Nimbu ka Aachar)",
    nameHindi: "नींबू का अचार",
    category: "snacks",
    servingSize: 10,
    calories: 15,
    protein: 0.1,
    carbs: 2.2,
    fat: 0.6,
    fiber: 0.4,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["pickle", "aachar", "accompaniment"]
  },
  {
    name: "Chilli Pickle (Hari Mirch ka Aachar)",
    nameHindi: "हरी मिर्च का अचार",
    category: "snacks",
    servingSize: 10,
    calories: 25,
    protein: 0.2,
    carbs: 0.8,
    fat: 2.4,
    fiber: 0.3,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["pickle", "aachar", "spicy"]
  },
  {
    name: "Mixed Vegetable Pickle",
    nameHindi: "मिश्रित अचार",
    category: "snacks",
    servingSize: 10,
    calories: 28,
    protein: 0.1,
    carbs: 0.9,
    fat: 2.7,
    fiber: 0.3,
    isVegetarian: true,
    isVegan: true,
    isJain: false,
    tags: ["pickle", "aachar", "mixed"]
  },
  // ================= EVERYDAY DAILY STAPLES =================
  {
    name: "Moong Dal Khichdi",
    nameHindi: "मूंग दाल खिचड़ी",
    category: "rice",
    servingSize: 150,
    calories: 165,
    protein: 5.2,
    carbs: 30,
    fat: 2.7,
    fiber: 3.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["comfort-food", "easy-to-digest", "staple"]
  },
  {
    name: "Plain Curd (Dahi)",
    nameHindi: "सादा दही",
    category: "snacks",
    servingSize: 100,
    calories: 60,
    protein: 3.2,
    carbs: 4.5,
    fat: 3.3,
    fiber: 0,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["probiotic", "calcium-rich", "staple"]
  },
  {
    name: "Plain Chapati (Roti)",
    nameHindi: "रोटी / चपाती",
    category: "breads",
    servingSize: 40,
    calories: 105,
    protein: 3.2,
    carbs: 21,
    fat: 1.0,
    fiber: 3.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["staple", "daily-bread", "whole-wheat"]
  },
  {
    name: "Boiled Basmati Rice",
    nameHindi: "उबले बासमती चावल",
    category: "rice",
    servingSize: 150,
    calories: 195,
    protein: 4.0,
    carbs: 42,
    fat: 0.4,
    fiber: 0.6,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["rice", "staple", "daily-carb"]
  },
  {
    name: "Moong Dal Tadka",
    nameHindi: "मूंग दाल तड़का",
    category: "dal",
    servingSize: 150,
    calories: 142,
    protein: 7.5,
    carbs: 21,
    fat: 3.3,
    fiber: 4.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["protein-rich", "staple", "daily-lentil"]
  },
  {
    name: "Vegetable Poha",
    nameHindi: "सब्जी पोहा",
    category: "snacks",
    servingSize: 100,
    calories: 160,
    protein: 3.0,
    carbs: 28,
    fat: 4.0,
    fiber: 2.0,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["breakfast", "light-meal", "staple"]
  },
  {
    name: "Rava Upma",
    nameHindi: "सूजी उपमा",
    category: "snacks",
    servingSize: 100,
    calories: 180,
    protein: 3.5,
    carbs: 30,
    fat: 5.0,
    fiber: 2.5,
    isVegetarian: true,
    isVegan: true,
    isJain: true,
    tags: ["breakfast", "staple", "semolina"]
  },
  {
    name: "Wheat Atta Roti (with Ghee)",
    nameHindi: "घी लगी रोटी",
    category: "breads",
    servingSize: 45,
    calories: 135,
    protein: 3.3,
    carbs: 21,
    fat: 4.5,
    fiber: 3.0,
    isVegetarian: true,
    isVegan: false,
    isJain: true,
    tags: ["staple", "daily-bread", "ghee"]
  }
];

const seedDB = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/fitgoal';
    await mongoose.connect(mongoUri);
    console.log('Connected to MongoDB for Indian Foods seeding...');

    // Clear collection
    await IndianFood.deleteMany({});
    console.log('Cleared existing IndianFood documents.');

    // Insert seeds
    const created = await IndianFood.create(foods);
    console.log(`Successfully seeded ${created.length} Indian food items.`);

    await mongoose.connection.close();
    console.log('Database connection closed.');
  } catch (error) {
    console.error('Seeding Indian Foods failed:', error);
    process.exit(1);
  }
};

seedDB();
